Added `check-smtp-ehlo` for checking whether SMTP is functional
sensu-plugins/sensu-plugins-postfix pull request #7
Opened 2016-11-29 12:27 UTC by hanynowsky

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatablity Issues

2017-01-08 19:11 UTC, GhostLyrics commented on CHANGELOG.md
> +- metrics-mailq.rb: do not output stderr when the mail queue is empty
I think you should remove this, since this PR does not touch said file.

2017-05-29 04:34 UTC, majormoses commented on CHANGELOG.md
> +- metrics-mailq.rb: do not output stderr when the mail queue is empty
agreed

2017-05-29 04:36 UTC, majormoses commented
@hanynowsky any chance on giving this another go?

2017-05-30 13:27 UTC, hanynowsky commented
Sure. Please gimme a week. I am on a hot project.

2017-05-30 15:54 UTC, majormoses requested changes

2017-05-30 15:54 UTC, majormoses commented on bin/check-smtp-ehlo.rb
> +    ok "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-smtp-ehlo.rb \
remove these hardcoded paths.

2017-05-30 15:54 UTC, majormoses commented on bin/check-smtp-ehlo.rb
> +    --warn-only --domain google.com --hostname localhost --port 25 \
remove hardcoded domain, hostname, port.

2017-05-30 15:54 UTC, majormoses commented on bin/check-smtp-ehlo.rb
> +  option(
we don't need this I believe as it should come from the base class plugin.

2017-05-30 15:54 UTC, majormoses commented on bin/check-smtp-ehlo.rb
> +    --smtpbind has priority" if config[:help]
huh?

2017-07-20 01:27 UTC, majormoses commented
closing due to inactivity, please reply back if you would like to see this through so I can re-open.

2017-07-20 01:27 UTC, closed without merging